- src: https://github.com/rhpvorderman/ansible-galaxy.git
  name: galaxyproject.galaxy
  version: tooldata
- src: https://github.com/galaxyproject/ansible-miniconda.git
  name: galaxyproject.miniconda
